### ISSUE TITLE
Errors while rendering by googlebot

### ISSUE THREAD

**Issue by Azumi0** [EfogDev/react-services-injector#1]
While using "Feth & render" from google webmasters console i am getting a very rude error "Looks like you're using a fucking ios". Clearly I am not using "a fucking ios".

![2017-08-06 18_09_12-search console pobierz jako google - http___cdoc pl_](https://user-images.githubusercontent.com/17425166/29005010-9c94323e-7ad2-11e7-9136-7bb7f21c1326.png)

The code that "undefined" error is referencing to is 
```
ConnectedComponent.prototype.componentWillMount = function componentWillMount() {
                this.__injector_key = injector.connectInstance(this);
                this.services = Object.assign({}, injector.get());

                if (_component.prototype.componentWillMount) _component.prototype.componentWillMount.call(this);
            };
```

Any help would be greatly appreciated.

**Comment by efogdev** [comment]
Hey! I'm sorry you're having issues with the library.
It is in very-alpha state right now and I didn't think someone except me will use it.
I'm not at home and I won't be for about 2 or 3 days, but I guess you're using `import {something } from "react-services-injector";`
Please, try to import from "react-services-injector/index.es5" (in every file you're using injector) - that's a transpiled version of the library.

Please, let me know if the problem won't be fixed. I'm going to finish the library in the nearest future so any reports are really helpful.

**Comment by Azumi0** [comment]
Thanks for quick reply.
I am already using index.es5 version, without it I couldn't compile my app to production version by `webpack -p`. 
I found two issues: "Object.assign" is not a function for google renderer, and the error that triggers "ios" message says "Cannot redefine property 'name'"

**Comment by efogdev** [comment]
Do you have `babel-polyfill` in your project? Should work with it. 
If you have some reasons to not to install it, I won't be able to help you, because, as I said before, I'm not at home.
You can either install `babel-polyfill` or find any other Object.assign polyfill.

**Comment by Azumi0** [comment]
Thanks, that helped with Object.assign. Now It is only a matter of "ios" message 👍 Do you think you will be able to fix this issue anytime soon?

**Comment by efogdev** [comment]
Do you care about that error? The only problem is its roughness, the library will work properly.

Anyway, I can't publish new version to npm now, but I will do that ASAP.

**Comment by Azumi0** [comment]
Thanks! This library is totally awesome, maybe you should add to readme an entry about babel-polyfill? 
Anyway, you sir are the best!

**Comment by efogdev** [comment]
Hey, by the way, version 1.0.0-rc.1 is now available :) Library became much better I think.
//backward compatibility has been broken, but I've added polyfills for Object.assign and Promise so you don't need babel-polyfill now
